import Link from "next/link";
import { Role, listExplorerEvidence } from "@evidex/database";

export const dynamic = "force-dynamic";

type ExplorerRoleFilter = "ALL" | "ADMIN" | "USER";

function parseRoleFilter(value: string | undefined): ExplorerRoleFilter {
  if (value === Role.ADMIN) {
    return "ADMIN";
  }
  if (value === Role.USER) {
    return "USER";
  }
  return "ALL";
}

export default async function ExplorerPage({
  searchParams
}: {
  searchParams?: {
    role?: string;
  };
}) {
  const roleFilter = parseRoleFilter(searchParams?.role);
  const roleQuery = roleFilter === "ALL" ? "" : `?role=${roleFilter}`;
  const appBaseUrl = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";
  const shareUrl = `${appBaseUrl}/explorer${roleQuery}`;
  const csvUrl = `/api/explorer${roleQuery ? `${roleQuery}&format=csv` : "?format=csv"}`;
  const liveJsonUrl = `/api/explorer${roleQuery ? `${roleQuery}&includeChain=true` : "?includeChain=true"}`;
  const evidences = await listExplorerEvidence({
    limit: 100,
    role: roleFilter === "ALL" ? undefined : roleFilter
  });

  return (
    <section className="space-y-6">
      <div className="space-y-3">
        <h1 className="text-3xl font-bold">Evidence Explorer</h1>
        <p className="text-sm text-cloud/70">
          Shareable on-chain blocks/extrinsics generated by admin and user accounts.
        </p>
        <div className="card space-y-2 text-xs text-cloud/70">
          <p className="font-medium text-cloud">Share URL</p>
          <p className="font-mono break-all">{shareUrl}</p>
          <div className="flex flex-wrap gap-2">
            <a href={csvUrl} className="btn-secondary" target="_blank" rel="noreferrer">
              Export CSV
            </a>
            <a href={liveJsonUrl} className="btn-secondary" target="_blank" rel="noreferrer">
              Live Chain JSON
            </a>
          </div>
        </div>
        <div className="flex flex-wrap gap-2">
          <Link href="/explorer" className={`btn-secondary ${roleFilter === "ALL" ? "border-accent text-accent" : ""}`}>
            All Blocks
          </Link>
          <Link
            href="/explorer?role=ADMIN"
            className={`btn-secondary ${roleFilter === "ADMIN" ? "border-accent text-accent" : ""}`}
          >
            Admin Blocks
          </Link>
          <Link
            href="/explorer?role=USER"
            className={`btn-secondary ${roleFilter === "USER" ? "border-accent text-accent" : ""}`}
          >
            User Blocks
          </Link>
        </div>
      </div>
      <div className="grid gap-4">
        {evidences.map((evidence) => (
          <article key={evidence.id} className="card flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
            <div className="space-y-1">
              <p className="text-sm text-cloud/60">{evidence.chain}</p>
              <h2 className="text-lg font-semibold">{evidence.originalFilename}</h2>
              <p className="font-mono text-xs text-cloud/70">{evidence.sha256Hash}</p>
              <p className="text-xs text-cloud/70">
                Generated by: {evidence.user.name ?? evidence.user.walletAddress} ({evidence.user.role})
              </p>
              <p className="font-mono text-xs text-cloud/70">Tx: {evidence.chainTxHash}</p>
            </div>
            <div className="flex gap-3">
              <Link href={`/evidence/${evidence.id}`} className="btn-secondary">
                Details
              </Link>
              {evidence.anchors[0]?.explorerUrl ? (
                <a href={evidence.anchors[0].explorerUrl} target="_blank" className="btn-primary" rel="noreferrer">
                  Open Block
                </a>
              ) : null}
            </div>
          </article>
        ))}
        {!evidences.length ? <div className="card text-sm text-cloud/70">No blocks found for this filter.</div> : null}
      </div>
    </section>
  );
}
