/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface EvidenceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "commitMerkleRoot"
      | "crossChainProofs"
      | "getEvidenceByHash"
      | "getUserEvidence"
      | "merkleRoots"
      | "registerEvidence"
      | "trustedAnchor"
      | "verifyEvidence"
      | "verifyEvidenceWithMerkle"
      | "verifyFromPolkadot"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CrossChainVerified"
      | "EvidenceRegistered"
      | "MerkleRootCommitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "commitMerkleRoot",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "crossChainProofs",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvidenceByHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserEvidence",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "merkleRoots",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerEvidence",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedAnchor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyEvidence",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyEvidenceWithMerkle",
    values: [BytesLike, BytesLike[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyFromPolkadot",
    values: [BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "commitMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "crossChainProofs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvidenceByHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "merkleRoots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedAnchor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyEvidenceWithMerkle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyFromPolkadot",
    data: BytesLike
  ): Result;
}

export namespace CrossChainVerifiedEvent {
  export type InputTuple = [
    hash: BytesLike,
    polkadotTxHash: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    hash: string,
    polkadotTxHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    hash: string;
    polkadotTxHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvidenceRegisteredEvent {
  export type InputTuple = [
    hash: BytesLike,
    owner: AddressLike,
    ipfsCID: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    hash: string,
    owner: string,
    ipfsCID: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    hash: string;
    owner: string;
    ipfsCID: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MerkleRootCommittedEvent {
  export type InputTuple = [
    root: BytesLike,
    polkadotTxHash: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    root: string,
    polkadotTxHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    root: string;
    polkadotTxHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EvidenceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): EvidenceRegistry;
  waitForDeployment(): Promise<this>;

  interface: EvidenceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  commitMerkleRoot: TypedContractMethod<
    [root: BytesLike, polkadotTxHash: string],
    [void],
    "nonpayable"
  >;

  crossChainProofs: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  getEvidenceByHash: TypedContractMethod<
    [hash: BytesLike],
    [
      [string, bigint, string] & {
        owner: string;
        timestamp: bigint;
        ipfsCID: string;
      }
    ],
    "view"
  >;

  getUserEvidence: TypedContractMethod<
    [wallet: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;

  merkleRoots: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  registerEvidence: TypedContractMethod<
    [hash: BytesLike, ipfsCID: string],
    [void],
    "nonpayable"
  >;

  trustedAnchor: TypedContractMethod<[], [string], "view">;

  verifyEvidence: TypedContractMethod<
    [hash: BytesLike],
    [
      [boolean, bigint, string, string, string] & {
        exists: boolean;
        timestamp: bigint;
        owner: string;
        ipfsCID: string;
        polkadotProof: string;
      }
    ],
    "view"
  >;

  verifyEvidenceWithMerkle: TypedContractMethod<
    [hash: BytesLike, proof: BytesLike[], root: BytesLike],
    [void],
    "nonpayable"
  >;

  verifyFromPolkadot: TypedContractMethod<
    [hash: BytesLike, polkadotTxHash: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "commitMerkleRoot"
  ): TypedContractMethod<
    [root: BytesLike, polkadotTxHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "crossChainProofs"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getEvidenceByHash"
  ): TypedContractMethod<
    [hash: BytesLike],
    [
      [string, bigint, string] & {
        owner: string;
        timestamp: bigint;
        ipfsCID: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserEvidence"
  ): TypedContractMethod<
    [wallet: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "merkleRoots"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "registerEvidence"
  ): TypedContractMethod<
    [hash: BytesLike, ipfsCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "trustedAnchor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyEvidence"
  ): TypedContractMethod<
    [hash: BytesLike],
    [
      [boolean, bigint, string, string, string] & {
        exists: boolean;
        timestamp: bigint;
        owner: string;
        ipfsCID: string;
        polkadotProof: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyEvidenceWithMerkle"
  ): TypedContractMethod<
    [hash: BytesLike, proof: BytesLike[], root: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyFromPolkadot"
  ): TypedContractMethod<
    [hash: BytesLike, polkadotTxHash: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CrossChainVerified"
  ): TypedContractEvent<
    CrossChainVerifiedEvent.InputTuple,
    CrossChainVerifiedEvent.OutputTuple,
    CrossChainVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "EvidenceRegistered"
  ): TypedContractEvent<
    EvidenceRegisteredEvent.InputTuple,
    EvidenceRegisteredEvent.OutputTuple,
    EvidenceRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "MerkleRootCommitted"
  ): TypedContractEvent<
    MerkleRootCommittedEvent.InputTuple,
    MerkleRootCommittedEvent.OutputTuple,
    MerkleRootCommittedEvent.OutputObject
  >;

  filters: {
    "CrossChainVerified(bytes32,string,uint256)": TypedContractEvent<
      CrossChainVerifiedEvent.InputTuple,
      CrossChainVerifiedEvent.OutputTuple,
      CrossChainVerifiedEvent.OutputObject
    >;
    CrossChainVerified: TypedContractEvent<
      CrossChainVerifiedEvent.InputTuple,
      CrossChainVerifiedEvent.OutputTuple,
      CrossChainVerifiedEvent.OutputObject
    >;

    "EvidenceRegistered(bytes32,address,string,uint256)": TypedContractEvent<
      EvidenceRegisteredEvent.InputTuple,
      EvidenceRegisteredEvent.OutputTuple,
      EvidenceRegisteredEvent.OutputObject
    >;
    EvidenceRegistered: TypedContractEvent<
      EvidenceRegisteredEvent.InputTuple,
      EvidenceRegisteredEvent.OutputTuple,
      EvidenceRegisteredEvent.OutputObject
    >;

    "MerkleRootCommitted(bytes32,string,uint256)": TypedContractEvent<
      MerkleRootCommittedEvent.InputTuple,
      MerkleRootCommittedEvent.OutputTuple,
      MerkleRootCommittedEvent.OutputObject
    >;
    MerkleRootCommitted: TypedContractEvent<
      MerkleRootCommittedEvent.InputTuple,
      MerkleRootCommittedEvent.OutputTuple,
      MerkleRootCommittedEvent.OutputObject
    >;
  };
}
