/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface EvidenceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getEvidenceByHash"
      | "getUserEvidence"
      | "registerEvidence"
      | "verifyEvidence"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "EvidenceRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "getEvidenceByHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserEvidence",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerEvidence",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyEvidence",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getEvidenceByHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyEvidence",
    data: BytesLike
  ): Result;
}

export namespace EvidenceRegisteredEvent {
  export type InputTuple = [
    hash: BytesLike,
    owner: AddressLike,
    ipfsCID: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    hash: string,
    owner: string,
    ipfsCID: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    hash: string;
    owner: string;
    ipfsCID: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EvidenceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): EvidenceRegistry;
  waitForDeployment(): Promise<this>;

  interface: EvidenceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getEvidenceByHash: TypedContractMethod<
    [hash: BytesLike],
    [
      [string, bigint, string] & {
        owner: string;
        timestamp: bigint;
        ipfsCID: string;
      }
    ],
    "view"
  >;

  getUserEvidence: TypedContractMethod<
    [wallet: AddressLike],
    [string[]],
    "view"
  >;

  registerEvidence: TypedContractMethod<
    [hash: BytesLike, ipfsCID: string],
    [void],
    "nonpayable"
  >;

  verifyEvidence: TypedContractMethod<
    [hash: BytesLike],
    [
      [boolean, bigint, string, string] & {
        exists: boolean;
        timestamp: bigint;
        owner: string;
        ipfsCID: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getEvidenceByHash"
  ): TypedContractMethod<
    [hash: BytesLike],
    [
      [string, bigint, string] & {
        owner: string;
        timestamp: bigint;
        ipfsCID: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserEvidence"
  ): TypedContractMethod<[wallet: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "registerEvidence"
  ): TypedContractMethod<
    [hash: BytesLike, ipfsCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyEvidence"
  ): TypedContractMethod<
    [hash: BytesLike],
    [
      [boolean, bigint, string, string] & {
        exists: boolean;
        timestamp: bigint;
        owner: string;
        ipfsCID: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "EvidenceRegistered"
  ): TypedContractEvent<
    EvidenceRegisteredEvent.InputTuple,
    EvidenceRegisteredEvent.OutputTuple,
    EvidenceRegisteredEvent.OutputObject
  >;

  filters: {
    "EvidenceRegistered(bytes32,address,string,uint256)": TypedContractEvent<
      EvidenceRegisteredEvent.InputTuple,
      EvidenceRegisteredEvent.OutputTuple,
      EvidenceRegisteredEvent.OutputObject
    >;
    EvidenceRegistered: TypedContractEvent<
      EvidenceRegisteredEvent.InputTuple,
      EvidenceRegisteredEvent.OutputTuple,
      EvidenceRegisteredEvent.OutputObject
    >;
  };
}
